version: '3.7'

services:
  ngrok:
    image: ngrok/ngrok:latest
    command: http web:8000
    volumes:
      - type: bind
        source: ./ngrok
        target: /var/lib/ngrok
    ports:
      - "4040:4040"
    networks:
      - app-net
