version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python ${PROJECTNAME}/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
    networks:
      - app-net

networks:
  app-net:
