version: '3.7'

services:

  db:
    image: mariadb:10.6
    ports:
      - "3307:3306"
    volumes:
      - mydb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app-net

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
    networks:
      - app-net

networks:
  app-net:

volumes:
  mydb:
    external: true
