# Generated by Django 4.1.3 on 2023-09-04 06:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0015_diary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diary',
            new_name='ch09_Diary',
        ),
    ]
