# Generated by Django 4.1.3 on 2023-09-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_rename_diary_ch09_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('_id', models.PositiveBigIntegerField()),
                ('sex', models.BooleanField(default=True)),
                ('num', models.PositiveBigIntegerField()),
            ],
        ),
    ]
