# Generated by Django 4.1.3 on 2023-08-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_mood_ch08_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mood',
            new_name='ch08_Mood',
        ),
    ]
