# Generated by Django 4.1.3 on 2023-08-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_rename_mood_ch08_mood'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ch08_post',
            options={'ordering': ('pub_time',)},
        ),
    ]
